"""Assemble docs/NUMBERS.md from results/*.json + results/numbers/*.json. Every item: number(s), one plain sentence, source.
Unknowns are written as MISSING lines, never guessed."""
import json, os, glob
T = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
R, N = T + "/results", T + "/results/numbers"
def J(p):
    try: return json.load(open(p))
    except Exception: return {}
swg, swgm, erin, erinm, occ, ace, comp, tnm, adb, shm, mg = (J(f"{N}/{k}.json") for k in ("num_swg_cohort", "num_swg_metrics", "num_erin_cohort", "num_erin_metrics", "num_occams", "num_aceb", "compute", "num_occams_tnm", "num_aceb_db", "swg_heatmaps", "num_medgemma"))
sa, pm, cc, sl2, svc, svc5, jury, lofo, unc, pan, panh, oof, tm, vlm, vlme, vlm0, occv3, wf, resp, cl = (J(f"{R}/{k}.json") for k in (
    "swg_selection_adjusted", "power_map_v2", "clustered_cis", "slide_labels_v2", "slide_vs_casemax", "svc_5class", "erin_jury_labels_summary", "lofo_jury", "unsure_characterization",
    "pancancer_jury", "pancancer_hardening", "swg_oof_analyses", "transfer_matrix_excl", "vlm_pretrain", "vlm_swg_excl", "vlm_swg", "occams_v3", "occams_withinfold", "oac_response", "closure_cpu"))
L = []
def H(t): L.append(f"\n## {t}\n")
def P(s): L.append(s)
def MISS(s): L.append(f"- **MISSING** — {s}")
def mr(d, unit=""): return (f"median {d['median']:g}{unit} (range {d['min']:g}–{d['max']:g}{unit}" + (f", n={d['n']}" if 'n' in d else "") + ")") if d else "n/a"
def g(d, *ks, default=None):
    for k in ks:
        if not isinstance(d, dict) or k not in d: return default
        d = d[k]
    return d
def pct(a, b): return f"{a} ({100*a/b:.1f}%)" if b else str(a)
P("# Numbers dossier — every count and result in one place\n")
P(f"Generated {__import__('datetime').date.today()} by `scripts/numbers/assemble_numbers_md.py` from committed result JSONs. Each item: the number, one sentence, the source file. Items I could not compute are marked **MISSING** with what is needed.\n")
P("Cohort key: **SWG** = Cambridge Barrett's progression cohort (H&E + sWGS); **ERIN** = Cambridge Barrett's surveillance reports + slides; **OCCAMS** = OAC resection/biopsy consortium slice; **ACE-B** = Dr di Pietro's Barrett's cohort (134 patients, 7× sWGS; slides being scanned) used only as an external validation set; **Hannah Coles set** = 221 OCCAMS OGD staging biopsies, not yet linked to patients.\n")

# ---------------- A ----------------
P("\n# A. Dataset descriptions\n")
H("1. Patients, cases/biopsy events, slides; slides per patient")
sd = swg.get("slides_on_disk_csv", {})
P(f"- **SWG:** {swg.get('patients')} patients, {swg.get('samples_rows')} biopsy samples in the frozen pre-event release; samples per patient {mr(swg.get('samples_per_patient'))}. Slides on disk: {sd.get('rows')} `.ndpi` across {sd.get('patients')} patients ({sd.get('with_patient')} attributable); slides per patient {mr(sd.get('slides_per_patient'))}. *(num_swg_cohort; docs/swg_barretts_slides.csv)*")
es, er = erin.get("slides", {}), erin.get("reports", {})
P(f"- **ERIN:** {er.get('patients')} patients, {er.get('n')} reports; {es.get('all_files')} slide files in {es.get('cases')} cases from {es.get('patients')} patients, of which {es.get('he_slides')} are H&E; H&E slides per case {mr(es.get('he_slides_per_case'))}, per patient {mr(es.get('he_slides_per_patient'))}. Total {es.get('total_tb')} TB. *(num_erin_cohort)*")
P(f"- **OCCAMS:** {occ.get('cases_with_slides')} cases with slides ({occ.get('slides_h5')} slide feature files); slides per case {mr(occ.get('slides_per_case'))}; {occ.get('master_rows_for_slide_cases')} of these cases have a clinical master row. *(num_occams)*")
ae = ace.get("endoscopy_per_patient", {}); ao = g(ace, "official_case_presence", "value_counts") or {}
P(f"- **ACE-B:** {g(ace,'cases_for_rehan','rows')} official study cases (list from Fitzgerald lab); {ae.get('patients')} patient codes with {ae.get('records')} endoscopy records in the Barrett's database view (per patient {mr(ae)}). No slides or features on the cluster yet. *(num_aceb; phd/aceb_meta, May 2026)*")
H("2. Source hospital(s), years of collection")
y = swg.get("years", {}); P(f"- **SWG:** Cambridge (Addenbrooke's) surveillance; biopsy dates {y.get('min')}–{y.get('max')}.")
y = er.get("years", {}); P(f"- **ERIN:** Cambridge University Hospitals histopathology; report dates {y.get('min')}–{y.get('max')} (busiest years {sorted(y.get('by_year',{}).items(), key=lambda kv:-kv[1])[:3]}).")
y = g(occ, "slide_cases", "diagnosis_years") or {}; P(f"- **OCCAMS:** UK multi-centre consortium; diagnosis years for the imaged cases {y.get('min')}–{y.get('max')}. Contributing centres per case are not in our master extract.")
P(f"- **ACE-B:** Addenbrooke's (Rehan); trial endoscopies (AFI/WLE dates on the official case list) {g(adb,'official_case_dates','AFI_min')} to {g(adb,'official_case_dates','AFI_max')}, by year {g(adb,'official_case_dates','AFI_by_year')}; in the Barrett's database the same participants have endoscopies from {g(adb,'endoscopies_db','date_min')} to {g(adb,'endoscopies_db','date_max')} (surveillance before and after the trial). *(num_aceb_db)*")
H("3. Tissue and cancer type breakdown")
P(f"- **SWG:** all Barrett's oesophagus surveillance biopsies (oesophageal); grade breakdown in item 8.")
P(f"- **ERIN:** organ metadata is known for {100*es.get('organ_meta_known_frac',0):.0f}% of slide files: {es.get('organ_meta_counts')}. Stain types: {es.get('stain_type_counts')}. Report specimen protocols (top): {er.get('SpecimenProtocol_top')}. The remaining organs come from the report gross description via jury v3 `site` (consensus builder not yet written).")
P(f"- **OCCAMS:** oesophageal adenocarcinoma by design; slide specimen mix {occ.get('specimen_mix_slides')} (RES = resection block, OGD = endoscopic biopsy, NOT-HE = IHC/special stain).")
P(f"- **ACE-B:** Seattle-protocol histology on the official case list: {ao.get('Histology_Seattle_Protocol')} (IM = intestinal metaplasia/NDBE, ID = indefinite).")
H("4. Disease status at entry and treatment status")
P(f"- **SWG:** grade of each patient's first release sample (codes 0=NDBE,1=IND,2=LGD,3=HGD,4=IMC): {swg.get('entry_grade_first_sample')}. All samples are pre-event by construction (taken before the first confirmed LGD+); no treatment fields in the release.")
P(f"- **ERIN:** first-report jury grade per patient: {g(erin,'jury_report_level','patient_first_report_grade')}. Treatment status is not a structured field; post-treatment surveillance appears as CANCER→NDBE transitions in the natural-history matrix (238 such transitions in the database export).")
sc = occ.get("slide_cases", {})
P(f"- **OCCAMS:** established cancer at entry; pre-treatment T {sc.get('pretreatment_T')}, N {sc.get('pretreatment_N')}. Neoadjuvant regimen (grouped): {sc.get('neoadjuvant_grouped')}.")
P(f"- **ACE-B:** {ao.get('Histology_Seattle_Protocol')} at trial entry; treatment status unknown to us.")
H("5. Modalities available and the all-modality intersection")
mi = swg.get("modality_intersection", {})
P(f"- **SWG:** H&E (UNI2 features on {g(swg,'uni2','slides_ok')} slides) + sWGS copy-number ({g(swg,'cnv','samples_with_cx')} samples, {g(swg,'cnv','patients')} patients). Both modalities: {mi.get('samples_uni2_and_cnv_in_manifest')} samples / {mi.get('patients')} patients (missing UNI2: {mi.get('manifest_samples_missing_uni2')}, missing CNV: {mi.get('manifest_samples_missing_cx')}).")
fe = erin.get("features", {}); jr = erin.get("jury_report_level", {})
P(f"- **ERIN:** reports (all {er.get('n')}) + H&E slides ({es.get('he_slides')}) + report-derived clinical fields; no genomics. Reports with an H&E slide on disk: {jr.get('reports_with_he_slide_on_disk')}; H&E slides with UNI2 features: {fe.get('he_slides_with_h5')} (without: {fe.get('he_slides_without_h5')}).")
gm = occ.get("genomics", {})
P(f"- **OCCAMS:** H&E ({occ.get('cases_with_slides')} cases) + WGS genomics ({gm.get('tsv_cases')} cases, {gm.get('tsv_cases_with_slides')} with slides) + clinical/survival ({occ.get('master_rows_for_slide_cases')} slide cases with a master row). All three with usable survival: **87 cases (58 deaths)** — attrition 276→145→141→87 (docs/occams_reference.md).")
P(f"- **ACE-B:** metadata only; {ao.get('found_in_barretts_db')} of the official cases were found in the Barrett's database.")
H("6. Label definition, source, positives")
P(f"- **SWG progression:** per-sample endpoint — the *next* biopsy after this sample shows LGD confirmed on two reads or worse (`NextBiopsyProgression_LGD2plus`); source = pathology follow-up in the Barrett's database. Positive samples {swg.get('positive_samples_next_biopsy_lgd2')}/{swg.get('samples_rows')} ({100*swg.get('positive_samples_next_biopsy_lgd2',0)/max(swg.get('samples_rows',1),1):.1f}%); progressor patients (any positive sample) **{swg.get('progressor_patients')}/{swg.get('patients')}** ({100*swg.get('progressor_patients',0)/max(swg.get('patients',1),1):.0f}%). The database's own `Progressor_label` flag marks {g(swg,'alt_Progressor_label_col','positive_patients')} patients — a stricter, different definition; the models use the former.")
jd = jury.get("label_dist_train_eligible", {}); pos = sum(jd.get(k, 0) for k in ("LGD", "HGD", "CANCER"))
P(f"- **ERIN grade:** NDBE vs LGD+ from the report; source = 8-model LLM jury. Train-eligible reports {jury.get('status_dist',{}).get('train_eligible')}, LGD+ {pct(pos, sum(jd.values()) or 1)}; at slide level 528/2,153 positive (24.5%).")
pc = erin.get("progression_cohort_v3", {})
P(f"- **ERIN progression:** index NDBE/IND report → any later HGD or cancer report (jury labels); {pc.get('progressors')}/{pc.get('patients')} patients ({100*pc.get('progressors',0)/max(pc.get('patients',1),1):.1f}%). Slide-level progression cohort 28/153.")
P(f"- **OCCAMS survival:** overall survival from the master table (vital_status/deceased_survival_days); 58 deaths / 87 in the fusion cohort. **TRG response:** Mandard TRG on the resection, 41 responders (TRG1–3) / 131 with an OGD slide (31%).")
te = adb.get("derived_timeline_from_trial_entry", {})
P(f"- **ACE-B (derived from the Barrett's-database scrape, LLM-jury grades on every report from trial entry onward):** of {te.get('participants_with_graded_reports')} participants with graded reports, baseline grade {te.get('baseline_grade')}; **prevalent HGD/cancer at entry {te.get('prevalent_HGD_or_cancer_at_baseline')}, progressed to HGD/cancer {te.get('progressed_to_HGD_or_cancer')}, non-progressors {te.get('non_progressors')}** — close to Leanne's 30 / 11 / 93 (our progressor count is higher because DB follow-up runs to 2026 and grades are LLM-derived, not trial-adjudicated). Leanne's split is the label to use; ours is the cross-check.")
H("7. Time structure: time points, follow-up, censoring")
pt = swg.get("progression_timing", {})
P(f"- **SWG:** samples per patient {mr(swg.get('samples_per_patient'))}; gap between consecutive biopsies {mr(pt.get('DaysToNextBiopsy_all'),' days')}; first-to-last sample span, progressors {mr(pt.get('first_to_last_sample_span_months_progressors'),' months')}, non-progressors {mr(pt.get('first_to_last_sample_span_months_nonprogressors'),' months')}. Non-progressors are censored at their last biopsy.")
P(f"- **ERIN:** reports per patient {mr(er.get('reports_per_patient'))}; {er.get('patients_with_ge2_reports')} patients have ≥2 reports; follow-up span for them {mr(er.get('followup_span_years_patients_ge2'),' y')}. Progression cohort v3: time to HGD+ in progressors {mr(pc.get('tte_days_progressors'),' days')}, follow-up in non-progressors {mr(pc.get('followup_days_nonprogressors'),' days')} (censored at last report).")
P(f"- **OCCAMS:** single time point per case (diagnostic biopsy and/or resection); survival: vital_status present for {g(occ,'survival_columns_found','vital_status')} slide cases, death dates {g(occ,'survival_columns_found','date_death')}, last-known-alive days {g(occ,'survival_columns_found','last_known_survival_days')}.")
P(f"- **ACE-B (DB-derived):** {g(adb,'endoscopies_db','participants_with_endoscopy')} participants with endoscopies in the database, {mr(g(adb,'endoscopies_db','per_participant'))} per participant; pathology reports from trial entry {mr(te.get('reports_per_participant'))} per participant; time to progression {mr(te.get('time_to_progression_days'),' days')}; follow-up of non-progressors {mr(te.get('followup_days_nonprogressors'),' days')} (≈5.3 y median).")
H("8. Grade distribution where a grade exists")
P(f"- **SWG slide level** (release samples, codes 0–4): {swg.get('grade_dist_sample_level_codes')}; **patient level (max grade):** {swg.get('grade_dist_patient_max')}. Slide-CSV grades on disk: {sd.get('grade_col_dist')}.")
P(f"- **ERIN report level (train-eligible):** {jd}; **patient level (max grade):** {jr.get('patient_max_grade')}; **slide level, section-resolved (1,538 dual-labelled):** {g(erin,'per_section','dual_labelled_slides','worst_grade')}; **section level ({g(erin,'per_section','reports_with_consensus')} reports):** {g(erin,'per_section','section_worst_grade_dist')}.")
P(f"- **OCCAMS:** TRG {sc.get('trg_score')}; resection pT {sc.get('resection_pT')}, pN {sc.get('resection_pN')}.")
P(f"- **ACE-B:** {ao.get('Histology_Seattle_Protocol')}.")
H("9. Missingness per modality")
P(f"- **SWG:** {mi.get('manifest_samples_missing_uni2')} release samples lack UNI2 features and {mi.get('manifest_samples_missing_cx')} lack a CNV complexity value; UNI2 index status {g(swg,'uni2','status_counts')}; 26 of {sd.get('rows')} slides on disk are unattributable to a patient.")
P(f"- **ERIN:** organ metadata missing for {100*(1-es.get('organ_meta_known_frac',0)):.0f}% of slide files; {fe.get('he_slides_without_h5')} H&E slides still lack features ({fe.get('failed_log_lines')} logged extraction failures); jury label unsure/held-out for {jury.get('status_dist',{}).get('unsure_held_out')} reports; no genomics at all.")
P(f"- **OCCAMS:** imaging∩genomics is the binding constraint (141 of 276 imaged cases have WGS; 87 also have survival). Recurrence date present for only {g(occ,'slide_cases','recurrence_date_nonnull')} of {occ.get('master_rows_for_slide_cases')} slide cases (and 540 of 2,393 master rows overall) — recurrence is under-recorded, not rare.")
P(f"- **ACE-B:** everything except the case list and endoscopy metadata is missing.")
H("10. Access status and what is pending")
P("- **SWG:** on cluster, canonical copy at `/mnt/scratche/slow/fmlab/datasets/imaging/SWGCohort/slides/` (567 GB, pseudonymised: accession numbers in filenames). Pending: 26 unattributable slides need Leanne's scanning log; grade-code map (R.5).")
P(f"- **ERIN:** on cluster; all-slides UNI2 extraction {fe.get('h5_files')} h5 done; jury v3 (site + specimen type per section) full corpus complete (80/80 shards), consensus builder pending. Pathologist re-grading pending (grading app live).")
P("- **OCCAMS:** on cluster; master CSV of 11 May 2026; genomics TSV 383 cases. Pending: nothing for the thesis; recurrence completeness limits any recurrence model.")
P(f"- **ACE-B:** metadata matched May 2026 ({ao.get('found_in_barretts_db')} found in DB); slide access and governance path (Fitzgerald lab / Tim Somerset) pending; no compute yet.")

# ---------------- B ----------------
P("\n# B. Barrett's-specific (SWG)\n")
H("11. Progressors vs non-progressors")
P(f"- **{swg.get('progressor_patients')} progressors / {swg.get('patients')-swg.get('progressor_patients',0)} non-progressors** ({swg.get('patients')} patients) under the model endpoint (any sample whose next biopsy is LGD2+); {swg.get('positive_samples_next_biopsy_lgd2')} positive samples of {swg.get('samples_rows')}. Under the database `Progressor_label` flag: {g(swg,'alt_Progressor_label_col','positive_patients')} progressor patients.")
H("12. Time to progression / follow-up")
P(f"- Progressors: time from sample to progression {mr(pt.get('Time_to_progression_all_nonnull_samples_days'),' days')} (≈3 years median); their samples sit {mr(pt.get('MonthsBeforeLastBiopsy_progressor_samples'),' months')} before the last biopsy; first-to-last biopsy span {mr(pt.get('first_to_last_sample_span_months_progressors'),' months')}. Non-progressors: span {mr(pt.get('first_to_last_sample_span_months_nonprogressors'),' months')}, samples {mr(pt.get('MonthsBeforeLastBiopsy_nonprogressor_samples'),' months')} before last biopsy. Biopsies per patient in the database {mr(pt.get('biopsies_total_for_patient'))}. Samples with progression within k years: {pt.get('Progress_in_k_sample_counts')}.")
H("13. How progression was defined")
P("- Endpoint is LGD confirmed on two independent reads (the release name `lgd2`) or any higher grade, using the strict pre-event design: only samples before the first qualifying diagnosis enter. Source: PROJECT_STATE lines below. Who confirmed the reads (pathologist review vs database grade) is stated in the release documentation, not re-verified here.")
for l in (swg.get("project_state_lines") or [])[:12]: P(f"  > {l.strip()}")
H("14. Case-control matching")
P("- Two different things are called 'matching' here. (a) **Slide↔sWGS file matching** (Rehan's Dec 2025–Feb 2026 work, `slide_matching.xlsx`, `matched_manifest.csv`): every one of the 707 release rows has a paired image and CNV sample; `matching_sensitivity.csv` shows the effect of match strictness — restricting to exact matches leaves 532 rows / 111 patients / 24 positives and late-mean AUC 0.723 (image 0.672, CNV 0.645), i.e. the fusion pattern holds but with fewer positives. (b) **Case-control matching in the epidemiological sense** — were non-progressors *selected* to resemble progressors on age/sex/segment length? PROJECT_STATE calls SWG an 'internal matched cohort' and Killcoyne 2020's discovery set was 45 progressors vs 43 non-progressors by design, which suggests selection rather than a consecutive series.")
MISS("(b) only: whether SWG non-progressors were selected to match progressors, and on what — ask Leanne; matters for how the 33% progressor rate (vs <1%/yr in practice) is described.")
H("15. CNV: platform, resolution, samples, timing")
P(f"- Platform: shallow whole-genome sequencing (sWGS) of the same biopsy as the slide; {g(swg,'cnv','samples_with_cx')} samples with a copy-number complexity value from {g(swg,'cnv','patients')} patients ({g(swg,'cnv','unique_cnv_ids')} unique CNV profiles; release notes 693). Per sample, i.e. per biopsy, time-matched to the slide by construction (same specimen).")
P("- Depth 0.4× (Rehan, 21 Sep 2026); bin size 50 kb, the Killcoyne 2020 pipeline (6 March 2026 slides: 'Sequencing depth 0.4x, Bin size 50kb'). ACE-B, by contrast, is sequenced at ~7× (item 25), so its CNV must be re-called at matched resolution/depth before the SWG CNV arm is applied.")
H("16. UNI2 embeddings")
u = swg.get("uni2", {})
P(f"- {u.get('slides_ok')} slides with UNI2 embeddings, {u.get('feat_dim')}-d; patches per slide {mr(u.get('patches_per_slide'))} — the release stores a fixed 256-tile subsample per slide, not all tissue tiles; 224-px tiles at 20× (release folder `uni2_tile224_lvl2`). ERIN for comparison: patches per slide {mr(fe.get('patches_per_slide_kept'))} at 0.5 mpp/224 px.")

# ---------------- C ----------------
P("\n# C. Barrett's results (current)\n")
H("17. Split strategy")
P(f"- Patient-level, 5 outer folds (`fold_id_rep01`), nested CV inside each fold for hyper-parameters; folds seen per family {swgm.get('folds_seen',{}).get('late_mean')}; seeds present {swgm.get('seeds_seen',{}).get('late_mean')} → **one repeat**; seeds differ per fold (one seed each), not per repeat. {swgm.get('design_note')}")
H("18. Per-arm AUROC / AUPRC with CIs")
arms = swgm.get("arms", {})
P("| arm | patient-level AUROC [95% CI] | AUPRC [95% CI] | sample-level AUROC |\n|---|---|---|---|")
for k in ("image_only", "cnv_only", "late_mean", "early_fusion", "intermediate_fusion", "coattention_fusion", "late_stack_logit"):
    a = arms.get(k, {}); p = a.get("patient_level", {}); s = a.get("sample_level", {})
    if p: P(f"| {k} | {p.get('auroc')} {p.get('auroc_ci')} | {p.get('auprc')} {p.get('auprc_ci')} | {s.get('auroc')} {s.get('auroc_ci')} |")
cb = swgm.get("clinical_baseline_current_grade", {})
P(f"- **Clinical baseline** (no clinical variables exist in the release; the pathologist grade of the biopsy used as the score): sample-level AUROC {cb.get('sample_level_auroc')}, patient-level (max grade) {cb.get('patient_level_auroc_max_grade')}.")
P(f"- CIs are 2,000-replicate patient-resampled bootstraps. Positives: {g(arms,'late_mean','patient_level','pos')} of {g(arms,'late_mean','patient_level','n')} patients. *(num_swg_metrics)*")
H("19. Sensitivity and specificity at a stated threshold")
P("- **Chosen operating rule (Rehan, 21 Sep 2026): lock sensitivity at 0.95 (and, as the no-miss standard, 1.0) and report the specificity that buys.** This is a rule-out framing: we refuse to miss progressors and ask how many non-progressors we can safely de-escalate. (Youden's J is just the threshold maximising sensitivity+specificity−1 — a symmetric default with no clinical weighting; kept below for reference only.) The March slides used the same family of convention, Spec@Sen90 and Sen@95.")
P("| arm (patient level) | spec @ sens 0.95 | flagged/n | NPV @ cohort prev (33%) | NPV @ 0.5%/yr | spec @ sens 1.0 | Youden sens/spec |\n|---|---|---|---|---|---|---|")
for k in ("late_mean", "image_only", "cnv_only", "early_fusion"):
    op = g(arms, k, "patient_level", "operating_points") or {}
    a, b, yj = op.get("at_sensitivity_0.95"), op.get("at_sensitivity_1.0"), op.get("youden")
    if a and b and yj:
        P(f"| {k} | {a['specificity']:.2f} | {a['n_flagged_of_n'][0]}/{a['n_flagged_of_n'][1]} | {a['npv_cohort_prevalence']:.3f} | {a['npv_at_0.5pct']:.4f} | {b['specificity']:.2f} | {yj['sensitivity']:.2f}/{yj['specificity']:.2f} |")
P("- Read: at sensitivity 0.95, specificity is the fraction of non-progressors the model would release from intensified surveillance; NPV at 0.5%/yr shows what that means at real-world progression rates (where almost any test has NPV > 0.99, so specificity, not NPV, is the discriminating number). Thresholds are set post hoc on out-of-fold predictions; in a deployment they would be fixed on training folds.")
P("- **What the field reports (checked 21 Sep 2026):** TissueCypher's independent blinded validation (Davison et al. 2020) gives sensitivity 29% / specificity 86% for its 3-tier risk class and 40% / 86% for 2-tier at 5 years; its clinical-utility study (Diehl et al. 2021) reports sensitivity 62.3%, specificity 79.8%, prevalence-adjusted NPV 97.4%. Killcoyne 2020 reports low/moderate/high risk classes rather than a single operating point. So the field's convention is **rule-in** (high specificity ~0.80–0.86, sensitivity 0.3–0.6). Our late-mean model at specificity 0.80 has sensitivity 0.62 — the same operating region as TissueCypher's 62%/80%. Recommendation: report both — spec at sens 0.95 (our rule-out standard) and sens at spec 0.80/0.86 (comparable to TissueCypher).")
H("20. Calibration")
for k in ("late_mean", "image_only"):
    c = g(arms, k, "patient_level", "calibration") or {}
    if c: P(f"- **{k}:** Brier {c['brier']:.3f}; calibration slope {c['calibration_slope']:.2f}, intercept {c['calibration_intercept']:.2f}; reliability (decile mean-pred → observed): {[(b['mean_pred'], b['obs_rate']) for b in c['reliability_bins']]}.")
P("- Also on file: late-mean minus GigaPath-histology Brier delta −0.048 [−0.085, −0.011] (results/latemean_vs_gigapath_paired.json). No reliability curve existed before this dossier.")
H("21. Headline configuration and alternatives")
P(f"- Headline was **late-mean fusion** (UNI2 ABMIL risk averaged with CNV risk): naive AUROC gain over image-only +{g(sa,'auc','observed_delta_vs_hist','late_mean')}, Holm p 0.0096. Alternatives (AUC minus image-only): {g(sa,'auc','observed_delta_vs_hist')}.")
P(f"- **Current state:** selection-adjusted p = {g(sa,'auc','fusion_arms','p_selection_adjusted')} (best-of-5 arms null 95th pct {g(sa,'auc','fusion_arms','null_t_q95')}); out-of-bag gain of the selected arm +{g(sa,'selection_honest_delta_auc','mean_oob_delta_of_selected_arm')} {g(sa,'selection_honest_delta_auc','ci')}. Winner's curse: late-mean wins {100*g(oof,'winners_curse','late_mean_win_rate',default=0):.0f}% of re-selections, optimism +{g(oof,'winners_curse','mean_winner_optimism_auprc')} AUPRC. **The fusion gain is not claimed; the honest effect is +0.016 AUC with a CI spanning zero.**")
H("22. Performance by time point")
bt = swgm.get("by_time_before_event", {})
for k in ("late_mean", "image_only", "cnv_only"):
    o = bt.get(k, {})
    if o: P(f"- **{k}:** progressor samples 0–12 m before the event vs all non-progressor samples AUROC {g(o,'0-12m','auroc')} (n_pos {g(o,'0-12m','n_progressor_samples')}); 12–36 m {g(o,'12-36m','auroc')} (n_pos {g(o,'12-36m','n_progressor_samples')}); >36 m {g(o,'>36m','auroc')} (n_pos {g(o,'>36m','n_progressor_samples')}). Progression-within-k-years horizons: " + "; ".join(f"{kk} AUROC {v['auroc']} (pos {v['n_pos']}/{v['n']})" for kk, v in o.items() if kk.startswith("Progress_in_")))
P("- Longitudinal models (drift features, GRU) did not beat the last-sample snapshot (results/swg_trajectory.json); histology adds nothing over current-CNV persistence for predicting the next biopsy's CNV (results/swg_trajectory_baselines.json).")
H("23. Interpretability outputs")
P("- CNV: per-arm importances mapped to genes exist (`data/lgd2_cnv_feature_gene_annotation.csv`; TP53/EGFR/CCND1 arms).")
P("- **Exists:** 5 attention overlays for the image-only ABMIL from the July hardening analysis (`chapter1_scientific_hardening_20260727/attention_overlays/`: cases AD0496, PR1_HIN_043, AHM1146, AD0425, PR1_ADH_069; 256 tiles each; top-10% attention share 0.11–0.45). The release stores 256-tile subsamples with level-2 coordinates and `model.pt` state-dicts for every family, so re-inference is cheap.")
sp_ = {f"{x['a']} vs {x['b']}": x["mean"] for x in shm.get("tile_ranking_spearman_by_model_pair", [])}
P(f"- **DONE 21 Sep — SWG same-slide, cross-model maps** (`feasibility/runs/swg_heatmaps/output/maps/`, 11 slides: the 5 prior cases + 3 top-scored progressors + 1 missed progressor + 2 false-positive non-progressors; each panel = tissue thumbnail, image-only attention, image-only per-tile risk, intermediate-fusion attention, CNV-conditioned co-attention, early-fusion per-tile risk). Tile-ranking agreement (mean Spearman over slides): image-only vs early-fusion **per-tile risk {sp_.get('image_tile_risk vs early_tile_risk')}** (the two models see the same tiles as risky); attention image-only vs intermediate {sp_.get('image_attention vs intermediate_attention')}, vs co-attention {sp_.get('image_attention vs coattention_attention')}; **attention vs per-tile risk {sp_.get('image_attention vs image_tile_risk')}** — attention weight and tile risk are unrelated, i.e. 'where the model looks' is not 'what the model calls dangerous', which is the argument for tile-level grade maps rather than attention maps. Caveat: the release holds only 256 tiles per slide, so maps are sparse.")
P("- **Running (submitted 21 Sep):** (i) ERIN tile-level grade maps — six-class MIL trained under case-max and under section labels, then every tile scored individually (per-tile grade, expected grade on a 0–5 sliding scale, attention) on the same 12 held-out slides for both models (`scripts/task_erin_tilemaps.py`); (ii) SWG same-slide comparison across release families (image-only attention, co-attention CNV-conditioned attention, per-tile risk for early fusion) on the 5 existing cases plus additional progressors — being written.")
H("24. What changed since the last lab presentation")
P("- **Two audiences.** Markowetz lab: last update ~a year ago → everything in this dossier is new to them (the Barrett's fusion work AND ERIN/OCCAMS/TCGA/LLM-labelling, which did not exist then). Fitzgerald lab: last update **6 March 2026**, Barrett's chapter only. Changes since 6 March, from those slides to now:")
P("| | 6 March 2026 (Fitzgerald slides) | Now (Sept 2026) |\n|---|---|---|")
P("| Cohort | 160 patients / 470 visits / 959 samples / 941 sWGS; grades NDBE 609, ID 74, LGD 155, HGD 84, IMC 36, OAC 1 | **Frozen strict pre-event release: 150 patients / 707 samples**; at-event and post-event rows removed; patient-level max grade NDBE 97 / IND 15 / LGD 38 |")
P("| Tasks | Six tasks (ever-progress, at-risk 1–5 y, next-biopsy progression, next-biopsy grade, days-to-progression) | **One pre-registered primary: next biopsy is LGD2+**; horizons kept only as descriptive time-point analyses (item 22) |")
P("| Validation | Repeated CV (5–50 folds), best model per task reported, no CIs | 5 patient-disjoint frozen folds, nested CV, **paired bootstrap CIs**, Holm family, permutation controls |")
P("| Headline numbers | Ever-progress: MM early-mean AUC 0.844, image 0.823, CNV 0.737, MoE 0.853; next-biopsy progression MoE 0.880 (Exclude LGD/HGD/IMC) | Late-mean **0.774** [0.687–0.849], image 0.731, CNV 0.663 (patient level, strict pre-event). Lower because at-event rows and post-hoc model selection are gone |")
P("| Fusion claim | 'Image performs well, CNV confirms, combination is better' | Naive gain +0.043 (Holm p 0.0096) **does not survive selection adjustment** (p 0.25; out-of-bag gain +0.016 [−0.106, +0.080]); winner's curse quantified (+0.027); **claim demoted** |")
P("| Fusion architecture | Early fusion > attention fusion; Mixture-of-Experts routing | Late-mean > early/intermediate/co-attention/stack-logit in the release; MoE not carried into the frozen release |")
P("| Encoders | UNI2 only | UNI2 vs GigaPath histology: only the Brier difference survives (encoder-conditional gain) |")
P("| Longitudinal ('next step 2' in March) | Planned | **Done, negative**: drift features and GRU do not beat the last sample; histology adds nothing over CNV persistence for next-CNV prediction |")
P("| Attention-guided patch selection ('next step 1') | Planned | Not pursued as such; attention analysis limited to the 8 interpreted LGD2+ cases; heat-maps not regenerated |")
P("| Power | Not addressed | Power map: minimum detectable fusion gain 0.075–0.10 at n=150 |")
P("| Operating points / calibration | Spec@Sen90, Sen@95 in tables; no calibration | Spec at sens 0.95/1.0 with NPV (item 19); Brier + calibration slope and reliability deciles (item 20) |")
P("| Complementarity | Routing analysis (image early / CNV late) | Likelihood-ratio tests: CNV adds to histology (p 0.007) and vice versa (p 3e-5) — information is complementary even though discrimination gain is unproven |")
P("| External validation | None | **ACE-B agreed** (item 25); ERIN↔SWG overlap audit found 36% shared patients, so ERIN is not an external cohort for SWG |")
P("| Beyond Barrett's | — | OCCAMS/TCGA fusion (null), PORPOISE baseline, LLM report jury (7,149 reports, validated on TCGA), section-level labels, VLM, OAC response (null) |")
H("25. ACE-B: what will be run and when")
P("- **What ACE-B is (Rehan, 21 Sep 2026):** Dr Massimiliano di Pietro's cohort (he owns it; we collaborate to validate the SWG multimodal model). Per Leanne: **134 patients, 294 samples, sWGS at ~7× depth** (SWG is 0.4×), CNV complete or near-complete. Groups: **11 progressors** (NDBE/LGD → HGD/IMC), **93 non-progressors**, **30 prevalent HGD/IMC** at baseline. Blocks: 44 at the ECI (Nottingham blocks), 250 in the Cambridge Tissue Bank store in Wales (pre-2023). Histopathology did not exist — **slides are being scanned now** (Histopathology Core; ~£369 for the 44 ECI blocks, ~£2,094 for the 250 Wales blocks; .svs output; 2-week turnaround; magnification and full-QC options still to choose).")
P(f"- Our May 2026 metadata match found {g(ace,'cases_for_rehan','rows')} study cases / {ae.get('patients')} patient codes in the Barrett's database (Seattle histology {ao.get('Histology_Seattle_Protocol')}) — these counts differ from Leanne's 134/294 and need reconciling once her sample list arrives.")
P("- **Plan (validation only, no training):** (1) featurise the scanned H&E with the identical UNI2 pipeline (20×/224 px; ~48 s/slide ⇒ under 1 GPU-h for the ~36–46 minimum slides, ~4 GPU-h for all 294); (2) obtain CNV from Dr di Pietro and **re-derive the SWG CNV representation at matched resolution** — 7× reads must be down-sampled or re-binned to the 0.4×/50 kb pipeline, otherwise the CNV arm sees a depth shift; (3) apply the frozen SWG image-only, CNV-only and late-mean models zero-shot; report AUROC/AUPRC and specificity at the SWG-fixed sensitivity-0.95 threshold (item 19). Minimum imaging plan from the proposal: 11 progressors (pre-cancer time point) + 20–25 matched non-progressors + optionally 5–10 prevalent HGD/IMC ≈ 36–46 slides.")
P("- **What 11 progressors can and cannot show:** with 11 positives and ~25–93 negatives the 95% CI on an AUROC near 0.75 is roughly ±0.15, so ACE-B can confirm that the model transfers (AUROC clearly above 0.5) but **cannot** decide whether fusion beats image-only (a 0.04 difference is far below detectability). The pre-registration should say so. Two further shifts to declare up front: scanner/format (Aperio .svs vs the SWG Hamamatsu .ndpi) and sequencing depth.")
P(f"- **From the database scrape (num_aceb_db):** 125 of the 153 official cases resolve to a DB participant; 120 have endoscopy records (median 8), 123 have pathology reports (1,024 in total, 977 jury-graded). Anchored at trial entry: {te.get('prevalent_HGD_or_cancer_at_baseline')} prevalent HGD/cancer, {te.get('progressed_to_HGD_or_cancer')} progressors (median {g(te,'time_to_progression_days','median')} days to progression), {te.get('non_progressors')} non-progressors with median {g(te,'followup_days_nonprogressors','median')} days follow-up — so the DB can supply dates, grades and follow-up for the validation set even before Dr di Pietro's tables arrive; per-participant timeline in `feasibility/runs/num_aceb_db_v2/output/aceb_participant_timeline.csv` (cluster).")
MISS("timing — depends on scanning completion and Dr di Pietro releasing the CNV; nothing else to compute until slides arrive.")

# ---------------- D ----------------
P("\n# D. ERIN labelling (LLM jury)\n")
H("26. Reports total, oesophageal subset, matched slide")
P(f"- {er.get('n')} reports from {er.get('patients')} patients; {jr.get('reports_with_any_slide_file')} reports have any slide file and {jr.get('reports_with_he_slide_on_disk')} an H&E slide; the original one-slide-per-case imaging set covered {g(erin,'imaged_cases_original_one_per_case','cases')} cases.")
P(f"- Oesophageal subset: slide-file organ metadata says {es.get('organ_meta_counts')}; report specimen protocols {er.get('SpecimenProtocol_top')}. An exact oesophagus-only report count needs the jury v3 `site` consensus (pending).")
H("27. Jury composition")
P(f"- Whole-report jury: 8 open-weight models via local ollama — {g(erin,'inter_model_agreement_full_corpus','models')}. Prompt: one report per request, strict JSON, five-rung ladder NDBE<IND<LGD<HGD<CANCER. Aggregation: majority label; jury_frac ≥ 0.75 → train-eligible, else unsure held out; 78 hardest disagreements adjudicated by hand. Per-section jury (v2): 5 jurors, grade accepted with ≥3/5, section kept if seen by ≥max(3, n−2) jurors; v3 adds `site` and `specimen_type`.")
H("28. Agreement")
ia = erin.get("inter_model_agreement_full_corpus", {})
P(f"- Inter-model (full corpus, {ia.get('n_reports_all_models')} reports graded by all 8): mean pairwise agreement {ia.get('mean_pairwise_agreement')} (range {ia.get('min_pairwise')}–{ia.get('max_pairwise')}), Fleiss' kappa {ia.get('fleiss_kappa')}, unanimous on {100*ia.get('frac_unanimous',0):.1f}% of reports. Leave-one-family-out flips ≤ {100*g(lofo,'verdict','max_flip_rate',default=0):.1f}% of labels.")
P(f"- External human anchor: TCGA registry grade, two-tier agreement ESCA 0.971 (n=102), STAD 0.964 (335), KIRC 0.964 (477) vs majority baselines 0.64/0.60/0.56 (results/pancancer_hardening.json).")
P("- **Pathologist-labelled ERIN subset: none exists.** The 78 adjudications were text re-reads by the research engineer, not a pathologist; 100-case hand-label key prepared, grading app live, no grades yet.")
H("29. Label distribution produced by the jury")
P(f"- Whole-report: {jury.get('label_dist_train_eligible')} (train-eligible {jury.get('status_dist',{}).get('train_eligible')}; unsure {jury.get('status_dist',{}).get('unsure_held_out')}; adjudicated {jury.get('status_dist',{}).get('adjudicated')}).")
ps = erin.get("per_section", {})
P(f"- Per-section ({ps.get('reports_with_consensus')} reports, sections per report {mr(ps.get('sections_per_report'))}): section worst-grade {ps.get('section_worst_grade_dist')}; cancer subtypes {ps.get('cancer_subtype_sections')}. Slide level: {g(ps,'dual_labelled_slides','worst_grade')} vs case-max {g(ps,'dual_labelled_slides','case_max')} — {100*g(ps,'dual_labelled_slides','frac_differ',default=0):.1f}% differ.")
H("30. Fine-tuned MedGemma vs zero-shot")
P("- **DONE 21 Sep (zero-shot, both sizes, via the ollama library — no Hugging Face gating needed).** Both MedGemma models graded all 7,149 ERIN reports with the identical whole-report prompt (`labeller/llm_grade_shard.py`, 8 shards × cuda/h200 twins; the 27B finished in under an hour).")
for tag, nm in (("medgemma27b", "MedGemma-27B (text)"), ("medgemma", "MedGemma-4B")):
    v = mg.get(tag, {}); aj = v.get("agreement_with_jury_train_eligible", {}); ad = v.get("vs_adjudication_cancer", {}); dc = v.get("disagree_with_confident_jury", {})
    P(f"- **{nm}:** parse rate {v.get('parse_rate')} ({v.get('parse_fail')} parse failures, {v.get('na')} NA); label distribution {v.get('label_dist')}. Agreement with the 8-model jury on train-eligible reports (n={aj.get('n')}): exact {aj.get('exact')}, binary NDBE/IND vs LGD+ {aj.get('binary_LGDplus')}. Versus the human adjudications (cancer yes/no, n={ad.get('n')}): accuracy {ad.get('accuracy')}, sensitivity {ad.get('sens')}, specificity {ad.get('spec')}. Disagrees with a near-unanimous jury (≥7/8) on {dc.get('n_disagree')}/{dc.get('n_confident')} reports; commonest patterns {[f'{a}: {b}' for a, b in (dc.get('pattern') or [])[:3]]}. Pairwise agreement with individual jurors {v.get('pairwise_agreement_with_each_juror')}.")
P("- **Reading:** the 27B behaves like a competent extra juror; its dominant disagreement with the jury is calling **HGD where the jury (and the adjudicators) say CANCER** — a systematic under-call of carcinoma, which is exactly the failure mode a medical-tuned model should NOT have and is worth a slide. On the adjudicated cancer cases its sensitivity is low (it misses cancers the jury catches) with perfect specificity. The 4B fails to return valid JSON on a quarter of reports and is not usable as a juror without prompt work. Fine-tuning (LoRA on the 4B, ~3–4 GPU-h) remains optional.")
P("- **Original plan/estimate (kept for the record).** MedGemma (Google, Gemma-3-based, medically tuned; 4B multimodal and 27B text-only instruction-tuned) is gated on Hugging Face: the API sees the repos but the download was refused ('not in the authorized list') — **the HF account behind the cluster token must accept the Health AI Developer Foundations terms**; not available in the ollama library either. Once access is granted: zero-shot 27B as a 9th juror with the identical JSON prompt over 7,149 reports ≈ 3–4 GPU-h on one H200 (weights 54 GB bf16), sharded 8 ways ≈ 1 h wall; 4B ≈ 1 GPU-h. Deliverable: agreement with the 8-model jury and with the 78 adjudications, added to items 27–28. LoRA fine-tune of the 4B on the 6,867 jury-labelled reports (held-out = the 78 adjudicated + a jury-labelled fold) ≈ 3–4 GPU-h more. Both fit before Thursday IF access is granted by Tuesday.")
H("31. Throughput and cost")
cp = comp.get("by_project", {})
P(f"- GPU-hours by campaign (allocated GPUs × wall time, incl. race-twin duplicates): whole-report jury {g(cp,'llm_jury_whole_report','gpu_h')} GPU-h for 7,149 reports × 8 models (≈{7149*8/max(g(cp,'llm_jury_whole_report','gpu_h',default=1),1):.0f} report-gradings per GPU-h); per-section v2 {g(cp,'llm_jury_sections_v2','gpu_h')} GPU-h; v3 {g(cp,'llm_jury_sections_v3','gpu_h')} GPU-h (9 jurors). Hardware: L40S (cuda partition) and H200 (preemptible). CPU inference was abandoned: {g(cp,'llm_jury_sections_v2','cpu_h')} CPU-h produced parse failures only.")

# ---------------- E ----------------
P("\n# E. ERIN image side\n")
H("32. Slides with UNI2 features vs remaining; patches total")
P(f"- {fe.get('h5_files')} feature files; {fe.get('he_slides_with_h5')} of {es.get('he_slides')} H&E slides done, {fe.get('he_slides_without_h5')} remaining ({fe.get('failed_log_lines')} logged failures). Total kept tissue patches **{fe.get('patches_total_kept'):,}**; per slide {mr(fe.get('patches_per_slide_kept'))}; grid tiles per slide {mr(fe.get('grid_tiles_per_slide'))}. {fe.get('tile')}.")
H("33. Task definition (per-section vs case-max)")
P(f"- {erinm.get('task_binary')}. Six-class: {erinm.get('task_sixclass')}. The label under test is the *training* label (report worst grade vs the slide's own section grade); the evaluation truth is always the section grade.")
H("34. Split, folds, metrics for both schemes")
P(f"- {erinm.get('split')}. CIs are patient-clustered bootstraps (2,000).")
b = erinm.get("binary", {}).get("arms", {})
P("| scheme | AUROC [CI] | AUPRC [CI] | F1@0.5 | F1@Youden (sens/spec) | spec @ sens 0.95 | spec @ sens 1.0 |\n|---|---|---|---|---|---|---|")
for k, v in b.items(): P(f"| {k} | {v['auroc']} {v['auroc_ci']} | {v['auprc']} {v['auprc_ci']} | {v['f1_at_0.5']} | {v['f1_at_youden']} ({v['sens_spec_at_youden'][0]}/{v['sens_spec_at_youden'][1]}) | {v.get('spec_at_sens_0.95')} | {v.get('spec_at_sens_1.0')} |")
s6 = erinm.get("sixclass", {}).get("arms", {})
P("\n| scheme (6-class) | macro AUROC [CI] | macro AUPRC | macro F1 [CI] | balanced acc |\n|---|---|---|---|---|")
for k, v in s6.items(): P(f"| {k} | {v['macro_auroc_ovr']} {v['macro_auroc_ci']} | {v['macro_auprc_ovr']} | {v['macro_f1']} {v['macro_f1_ci']} | {v['balanced_accuracy']} |")
P(f"- Paired deltas (slide-label-trained minus case-max-trained): binary AUROC {g(svc,'eval_on_slide_truth','trained_slide_level','delta_vs_ref','mean')} {g(svc,'eval_on_slide_truth','trained_slide_level','delta_vs_ref','ci')}; six-class macro-AUROC {g(svc5,'delta_slide_minus_case','macro_auc','mean')} {g(svc5,'delta_slide_minus_case','macro_auc','ci')}; weighted kappa {g(svc5,'delta_slide_minus_case','qwk','mean')} {g(svc5,'delta_slide_minus_case','qwk','ci')}. Case-max is no worse for binary and better for six-class at this n.")
H("35. Cases with follow-up for a progression/outcome label")
P(f"- {er.get('patients_with_ge2_reports')} patients have ≥2 reports; progression cohort v3 {pc.get('patients')} patients / {pc.get('progressors')} progressors (report level); {g(erin,'imaged_cases_original_one_per_case','cases')} imaged cases give 153 index slides / 28 progressors at slide level. With all-slides features the slide-level cohort can be rebuilt from every imaged index case.")

# ---------------- F ----------------
P("\n# F. OCCAMS\n")
H("36. Patients behind the slides")
P(f"- **Main OCCAMS tree:** {occ.get('cases_with_slides')} cases (one patient each) behind {occ.get('slides_h5')} featurised slides ({occ.get('specimen_mix_slides')}); {occ.get('cases_with_OGD')} have a biopsy slide, {occ.get('cases_with_RES')} a resection slide, {occ.get('cases_with_both')} both.")
P("- **The '227' is the Hannah Coles batch: 221 .svs slides** scanned Mar–Jun 2026 (batches B8126 27+36, B8134 82+51, B8167 25), at `occams/wsi_data/occams_hannah_coles/`, **additional** to the 635 above and not yet featurised. 131 H&E + 90 IHC (HER2, MMR panel, p53, CK); all OGD staging biopsies per Will. Identifiers: 196 carry a PS (block) number, 16 an OCCAMS patient ID, 16 (B8167) neither. **Patients behind them: only 25 slides → 12 patients are resolvable** (OC-AH-001/003/005/596/609/610/611/613, OC-RS-007/027, OC-SH-051 + 1); the other 196 slides are unlinkable until Will supplies a PS→patient mapping (0 of the 78 PS numbers appear in his WGS-linked xlsx). Source: `hannah_coles_integration_summary.md` (28 Jul 2026) and your Slack thread with Will, 27 Jul.")
H("37. The genomic values and coverage")
P(f"- TP53 status (composite of {gm.get('columns')[:4] if gm.get('columns') else '?'}), ploidy, and whole-genome doubling; from WGS; {gm.get('tsv_cases')} cases in the TSV, {gm.get('tsv_cases_with_slides')} with slides, complete for all of them. Among slide cases: WGD {gm.get('WGD_dist_slide_cases')}, TP53-altered {gm.get('TP53_any_slide_cases')}/{gm.get('tsv_cases_with_slides')}.")
H("38. Treatment and outcome fields")
P(f"- Neoadjuvant (slide cases): {sc.get('neoadjuvant_grouped')}; broad category {sc.get('neoadjuvant_broadcategory')}. Adjuvant regimen recorded for {sc.get('adjuvant_regimen_nonnull')}.")
P(f"- Outcomes: TRG {sc.get('trg_score')} (n={sum((sc.get('trg_score') or {}).values())}); tumour_response {sc.get('tumour_response')}; recurrence date {sc.get('recurrence_date_nonnull')}/{occ.get('master_rows_for_slide_cases')}; survival fields {occ.get('survival_columns_found')}.")
H("39. Trainable labels (≥ ~30 positives)")
clp = occ.get("candidate_labels_positives", {}); pn = sc.get("resection_pN", {}) or {}
P(f"- Death: 58/87 ✔. TRG1–3 response: {g(clp,'TRG1-3_responders_among_OGD_slide_cases','pos')}/{g(clp,'TRG1-3_responders_among_OGD_slide_cases','n')} ✔ (run: null, UNI2 AUC {g(resp,'uni_v2','hist','auc')} {g(resp,'uni_v2','hist','auc_ci')}). TRG1–2: {g(clp,'TRG1-2_among_OGD_slide_cases','pos')} ✘. Node-positive at resection (pN1–3): {sum(v for k,v in pn.items() if k in ('n1','n2','n3'))}/{sum(pn.values())} ✔ (not yet modelled). WGD: {g(clp,'WGD_positive_slide_cases','pos')}/{g(clp,'WGD_positive_slide_cases','n')} ✔ (probes at chance). Recurrence: {g(clp,'recurrence_recorded_among_slide_cases','pos')} recorded ✘ (under-recorded).")

# ---------------- G ----------------
P("\n# G. OGD staging\n")
H("40. Slides, patients, stage/nodal labels, results")
P(f"- **Reading of 'OGD staging' (Rehan: probably TNM staging):** predicting the cancer's stage from the pre-treatment endoscopic (OGD) biopsy slide. Two slide pools exist: (a) the 221 Hannah Coles OGD staging biopsies (item 36) — **stage labels reachable for only 12 patients** until the PS→patient mapping arrives; (b) the {g(tnm,'ogd_biopsy_slide_cases','n_cases_with_master_row')} OGD-biopsy cases in the main tree that have a clinical master row, which already carry TNM.")
t = tnm.get("ogd_biopsy_slide_cases", {})
P(f"- **Stage labels on the {t.get('n_cases_with_master_row')} main-tree OGD cases** — clinical (pre-treatment) cT {t.get('clinical_cT')}, cN {t.get('clinical_cN')}, cM {t.get('clinical_cM')}; approximate AJCC7 stage group {t.get('clinical_stage_group_AJCC7_approx')}; **clinically node-positive {t.get('node_positive_clinical')}/{t.get('n_cases_with_master_row')}**. Pathological (post-neoadjuvant resection) ypT {t.get('path_pT')}, ypN {t.get('path_pN')}; **node-positive at resection {t.get('node_positive_path')}/{t.get('n_cases_with_master_row')}**; approximate stage group {t.get('path_stage_group_AJCC7_approx')}. Differentiation grade at diagnosis {t.get('grade_differentiation_diagnostic')}. *(num_occams_tnm; stage groups from T/N/M only)*")
P("- **Trainability:** node-positive (cN1–3: 96 vs 43 cN0; ypN1–3: 82 vs 51) and cT3 vs cT1–2 (111 vs 22) both clear the ~30-positive bar; full stage-group classification does not (most groups < 30). **No staging model has been run.** Nearest existing result on the same slides: pre-treatment biopsy → TRG response, NULL (UNI2 AUC 0.54; results/oac_response.json, which is local/uncommitted at your request).")
MISS("your confirmation that this reading is right; if so, a nodal-status (cN0 vs cN+) probe from the OGD biopsy is a one-script job on existing features.")

# ---------------- H ----------------
P("\n# H. Cross-project\n")
H("41. Shared code")
P("- Tiling + feature extraction: `scripts/extract_one_hf.py` (all encoders, all cohorts) and `campaigns/allslides/extract_worker.py` (pull-worker variant). MIL trainers: `scripts/abmil_clf.py`, `scripts/abmil_cox.py` (gated attention, Cox/CE heads, `bootstrap_auc`/`bootstrap_c`, `patient_folds`). Fusion: late fusion by z-scored risk averaging inside each task script; SWG release fusion families live in the Barrett's project. Evaluation: paired bootstrap, Holm, selection-adjusted permutation (`task_swg_selection_adjusted.py`), clustered CIs (`task_clustered_cis.py`), power map (`task_power_map.py`). Job pattern: `feasibility/run_task.sh` race-to-run. LLM jury: `labeller/llm_grade_shard.py`, `llm_grade_sections*.py`.")
H("42. Compute used per project")
P(f"- Window {comp.get('window')}: {comp.get('total_jobs'):,} jobs, **{comp.get('total_gpu_h'):,} GPU-h**, {comp.get('total_cpu_h'):,} CPU-h (GPU-h = allocated GPUs × wall time; race-twin duplicates that exited early are included, so real work is somewhat lower).")
P("| project | jobs | GPU-h | CPU-h |\n|---|---|---|---|")
for k, v in cp.items(): P(f"| {k} | {v['jobs']} | {v['gpu_h']} | {v['cpu_h']} |")
P(f"- Scaling rules of thumb: UNI2 extraction ≈ 48 s/slide on an L40S (all-ERIN 9,562 slides ≈ 130 GPU-h planned, {g(cp,'erin_allslides_extraction','gpu_h')} GPU-h used incl. twins); whole-report jury ≈ {g(cp,'llm_jury_whole_report','gpu_h')} GPU-h per 7k reports × 8 models; a 150-slide cohort like ACE-B is ~2 GPU-h to featurise and minutes to score.")
open(T + "/docs/NUMBERS.md", "w").write("\n".join(L) + "\n"); print("wrote docs/NUMBERS.md", len(L), "lines")
