"""Render the Results of docs/demographics_completion.md from results/paper_final/demographics/*.json; the pre-specification above '## Results' is kept
verbatim. Usage: python dm_render.py RESULTS_COMMIT"""
import json, sys
RC = sys.argv[1]; R = "results/paper_final/demographics"; DOC = "docs/demographics_completion.md"
J = lambda f: json.load(open(f"{R}/{f}.json"))
d1, d3, ag, s1, s2, unc = J("d1"), J("d3"), J("d3_agree"), J("d1_search"), J("d2_name_search"), J("d1_search_uncovered")
dd = json.load(open("results/paper_final/dataset_description/core.json"))["item4"]["setC"]
def table(h, rows): return ["| " + " | ".join(h) + " |", "|" + "|".join("---" for _ in h) + "|"] + ["| " + " | ".join(map(str, r)) + " |" for r in rows] + [""]
def num(o, N):
    return f"— (0/{N})" if not o or o.get("n", 0) == 0 else f"{o['median']} [{o['q1']}–{o['q3']}] ({o['n']}/{N})"
def cat(o, N):
    return f"— (0/{N})" if not o or o.get("n", 0) == 0 else ", ".join(f"{k} {v}" for k, v in o["counts"].items()) + f" ({o['n']}/{N})"
L = open(DOC).read().split("\n## Results")[0].rstrip().split("\n")
L += ["", "## Results", "", f"Pre-specification commit 24b2972; results commit {RC}. Scripts `scripts/paper_plan/dm_probe.py`, `dm_probe2.py`, `dm_probe3.R`, `dm_probe4.py`, `dm_namesearch.py`, `dm_supp.py`, `dm_st1.py`, `dm_analyse.py`, `dm_agree.py`, `dm_render.py`, all run through `scripts/cluster/campaign.sh` (prefixes dmp, dmc, dms, dmn, dmnx, dmp34, dmsu, dmst, dma, dmag, dmm). Results `results/paper_final/demographics/{{d1,d1_search,d1_search_uncovered,d2_name_search,d2_supp,d2_st_compare,d3,d3_agree}}.json`. Row-level tables on the cluster only: `feasibility/paper_plan/demographics/d1_crosstab_rows.csv`, `d3_patient_rows.csv`.", "",
      "Sources added by the search (both read for demographic columns only): `BE_Progression_Project.db` (SQLite, in `/mnt/scratche/slow/fmlab/zuberi01/phd/aceb_meta/`, a Django database of the BE progression project: 165 patients; table `Patient` columns Gender, AgeAtDiagnosis, SmokingStatus, Height, Weight, DateInitialDiagnosis, Circumference, Maximal, linked to study numbers through `AlternatePatientID`; its `Status` and `DateProgressed` columns were not read) and, for ACE-B, `aceb_sample_counts_per_patient_20260527_121448.csv` (a scrape of the Barrett's participant table: participant_id, gender, date_of_birth read; date_of_death not read).", ""]
L += ["### Status", ""] + table(["Item", "Status"], [["D1 database smoking field", f"{d1['d1_4_rule']['status']} (no codebook found; rule failed on agreement)"], ["D2 Killcoyne supplementary data", "DONE: supplementary appendix and all 14 Source Data files found on the cluster; Supplementary Table 1 compared"],
      ["D3 database-filled demographics", "DONE (with NOT AVAILABLE cells: database sex, ethnicity, family history; ACE-B age at first sample and dated Prague)"], ["D4 updated Table 1", "DONE"]])
# ---------- D1
c = d1["crosstab_dbcode_by_YN"]; codes = sorted(set(k for col in c.values() for k in col))
L += ["### D1. Database smoking field", "", "**Question.** What do the `initial_history.smoking` codes 0/1/2/3 mean? **Status.** " + d1["d1_4_rule"]["status"] + ". **Pre-specification.** Above (D1), decision rule committed in 24b2972 before the cross-tab.", "",
      f"**1. Definitions searched.** Database export tables and the report JSONs (`extras_report.json`, `match_report.json`, `match_report_v2.json`): no codebook. `occams_table_column.parquet` (660 rows, the OCCAMS column dictionary) defines `EX_IsSmoker` (current / former / never / unknown) and `EX_SmokingDurationYears` for the OCCAMS exposure form `ex_exposures_z1_0_0`, not the Barrett's `initial_history` table. Other smoking fields in `initial_history`: `packyears` (free text). No ex-smoker or quit-date column. "
      f"Code and text files referencing the database (`initial_history`/`initialhistory`/`barretts_db_export`) under {', '.join('`' + r + '`' for r in s1['code_search']['roots'])}: {len(s1['code_search']['files_referencing_db'])} files in {s1['code_search']['n_candidate_files']:,} candidate files (< 5 MB, code/text extensions; software folders excluded: conda/pixi environments, site-packages, R libraries, `.git`, and the two Python virtual environments `personal/scifi_video/env` and `env_tts`; {s1['code_search']['n_shards']} shards); lines in them mentioning smoking: {len(s1['code_search']['smoking_lines'])}"
      + (" (" + "; ".join(f"`{x[:160]}`" for x in s1["code_search"]["smoking_lines"][:6]) + ")" if s1["code_search"]["smoking_lines"] else "") + f". Dictionary-like file names (dictionary, codebook, lookup, schema, enum, form, `.sql`, `.mdb`, `.bak`): {len(s1['dictionary_like_names'])} paths, all library headers, backups of ID maps or SQL query templates; none defines the field. Not searched (listing did not finish after two re-splits; cancelled): {', '.join('`' + x + '`' for x in unc['not_searched'])}; searched with code and document extensions only: {', '.join('`' + x + '`' for x in s1['code_search'].get('codeonly_shards', [])) or 'none'}. The export code itself (`scripts/export_barretts_db.py`, `scripts/export_barretts_occams.py`) pulls whole tables from the database REST API (`api.barrettsdatabase.org.uk`) and defines no fields. The full path lists are in `d1_search.json`.", "",
      f"**2. Cross-tab** (Demographics_full rows {d1['demographics_rows']}; linked to the database: " + ", ".join(f"{k} {v}" for k, v in d1["linkage"].items()) + ").", ""]
L += table(["Database code", "Sheet Y", "Sheet N", "Sheet missing"], [[k, c.get("Y", {}).get(k, 0), c.get("N", {}).get(k, 0), c.get("missing", {}).get(k, 0)] for k in codes])
L += [f"Patients with a single database code and a Y/N value: n = {d1['crosstab_n']}. 'conflict:a/b' = the participant's records disagree; 'no_initial_history_row' = linked but no record.", ""]
sec = d1["secondary_not_prespecified"]["crosstab_dbcode_by_sqlite_SmokingStatus"]; sc = ["never", "former", "current", "None"]
L += ["Secondary, not pre-specified: database code against `BE_Progression_Project.db` Patient.SmokingStatus for the same rows.", ""] + table(["Database code"] + sc, [[k] + [sec.get(s, {}).get(k, 0) for s in sc] for k in codes])
p3 = d1["d1_3_prespecified"]; s3 = d1["d1_3_sensitivity_records_with_smoking_value"]
L += [f"**3. Default-value test.** Pre-specified: non-null fields per `initial_history` record median {p3['nonnull_fields_per_record']['median']} (range {p3['nonnull_fields_per_record']['min']}–{p3['nonnull_fields_per_record']['max']}, n {p3['nonnull_fields_per_record']['n']}); share of smoking = 0 in the lowest tercile {p3['smoking']['low']['share_0']}% (n {p3['smoking']['low']['n']}) vs the highest {p3['smoking']['high']['share_0']}% (n {p3['smoking']['high']['n']}): difference {p3['diff_low_minus_high_pp']} points, so by the rule 0 is **not** called a default. "
      f"The lowest tercile is made of records with every field null (3,024 records whose fields are all the string 'None'), so smoking is null there, not 0; the test is degenerate. Sensitivity (not pre-specified), records with any smoking value (n {s3['n']}): 0 is {s3['smoking']['low']['share_0']}% / {s3['smoking']['mid']['share_0']}% / {s3['smoking']['high']['share_0']}% across terciles (difference {s3['diff_low_minus_high_pp']} points, below 20).", ""]
oth = d1["d1_3_other_numeric_columns"]; z = [k for k, v in oth.items() if v["zero_is_mode"] and v["share_0_overall_nonnull"] >= 90]
L += [f"Other numeric-coded `initial_history` columns where 0 is the mode and ≥ 90% of non-null values: {', '.join('`' + k + '`' for k in z)} (for example `occupation` {oth['occupation']['share_0_overall_nonnull']}%, `highesteducation` {oth['highesteducation']['share_0_overall_nonnull']}%, `currentbmi` {oth['currentbmi']['share_0_overall_nonnull']}%, `bmi` {oth['bmi']['share_0_overall_nonnull']}%): the table stores 0 for 'not entered' in many fields. Columns with 0 rare: " + ", ".join(f"`{k}` {v['share_0_overall_nonnull']}%" for k, v in oth.items() if v["share_0_overall_nonnull"] < 10) + ".", ""]
r4 = d1["d1_4_rule"]
L += [f"**4. Decision.** Overlap |O| = {r4['overlap_n']} (≥ 20); 0 not treated as blank (by the pre-specified test); majority mapping {', '.join(f'{k} → {v}' for k, v in r4['candidate_mapping'].items())}; agreement {r4['agreement']}% (< 90%). **NOT RESOLVED**: smoking stays at the sheet values.", "",
      "**Method.** `dm_analyse.py` PART=d1: Demographics_full Study / Alternate Study Number → `pre_event_cohort.participant_id`, else `initial_history.hospitalnumber` / `patient_anonref`; database code = the single distinct non-null `smoking` value across the participant's records. **Sources.** `[DB]/initial_history.parquet`, `[DB]/occams_table_column.parquet`, `[SWG]/Demographics_full.csv`, `[REL]/pre_event_cohort.csv`, `aceb_meta/BE_Progression_Project.db`; `d1.json`, `d1_search.json`.",
      "**Caveats.** (1) Code 0 occurs among never, former and current smokers alike (secondary table), and the other columns' zeros point to 0 = not entered, but the pre-specified test did not establish it. (2) Codes 1–3 have too few overlapping patients (≤ 3 each) to map. (3) Only the Killcoyne discovery cohort has a Y/N reference, so 'all cohorts' reduces to 87 linked patients.", ""]
# ---------- D2
sp = J("d2_supp"); stc = J("d2_st_compare"); import re as _re
strict = _re.compile(r"moesm|supp_appendix|EGAD00001006033|killcoyne|s41591|41591_2020|supplementar|extended[_ -]?data|suppl", _re.I)
kh = s2["killcoyne_2020_files"]
L += ["### D2. Killcoyne 2020 supplementary data", "", "**Question.** Are the supplementary tables (especially Supplementary Table 1) available locally, and what do they add? **Status.** DONE (Supplementary Information PDF and Reporting Summary not on the cluster). **Pre-specification.** Above (D2).", "",
      f"**Search.** Lab scratch filenames ({s2['n_shards']} `lfs find` shards, {s2['n_files_listed']:,} files listed): {s2['n_hits']} hits on the pre-specified pattern, most of them false positives on the digits '1033' in slide and case names; {len(kh)} are Killcoyne 2020 files (`d2_name_search.json`): the main-text PDF (`s41591-020-1033-y.pdf`, 4 copies), the PMC supplementary appendix `EMS86618-supplement-Supp_Appendix.docx` (in `/mnt/scratche/fast/fmlab/zuberi01/personal/temp_hdd/Rehan/Downloads/Admin & Travel/`), and all 14 Nature Source Data files `41591_2020_1033_MOESM3`–`MOESM16_ESM.xlsx` in `/mnt/scratche/slow/fmlab/zuberi01/phd/killcoyne_data_from_paper/` (sizes identical to the files on nature.com). The Supplementary Information PDF (`MOESM1`) and Reporting Summary (`MOESM2`) are not on the cluster; the PMC appendix carries the same Supplementary Tables 1–4.",
      "`BarrettsProgressionRisk` (installed in `envs/killcoyne_r` and two clones, `phd/BarrettsProgressionRisk` and `paper/qc_historical_replay_plan_20260330/BarrettsProgressionRisk_repo`): `data/` holds only `ExampleQDNAseqData` (example `raw.data`, `fit.data`, `info`); `inst/extdata/` holds chromosome info files, the QDNAseq blacklist and an example `endoscopy.xlsx` with example QDNAseq counts; `R/sysdata` holds the fitted `be_model` and `rxRules`. No per-patient demographic or metadata file is shipped (`feasibility/paper_plan/demographics/probe3_pkg.txt`).",
      f"The 777-sample sheet has no demographic column: of its {len(ag['sheet777_columns'])} columns none holds age, sex, BE length, smoking or age at diagnosis (the only regex hit, 'Esophageal location', is a false positive).", "",
      "**What the files hold** (`d2_supp.json`): supplementary appendix tables: " + "; ".join(sp["docx_table_captions"]) + ". Source Data sheets: per-sample published probability, relative risk and risk class (MOESM4, Fig. 2a), per-sample status, oesophageal location, risk class and months before final (MOESM4 Fig. 2d, MOESM11), per-patient max probability and recommendations (MOESM5, MOESM6), complexity scores and copy-number values (MOESM3, MOESM7), validation probabilities, purity and ASCAT ratios (MOESM9), model tuning and bin-size results (MOESM10, MOESM12, MOESM15, MOESM16), p53 counts (MOESM13), QC example profiles (MOESM14). None holds per-patient demographics; the demographics exist only as the summaries of Supplementary Tables 1 and 2.", ""]
def ms(o): return "—" if not o or o.get("n", 0) < 2 else f"{o['mean']} ± {o['sd']}"
rows = [["Patients (NP / P)", "43 / 45", f"{stc['demographics_full_all']['NP']['patients']} / {stc['demographics_full_all']['P']['patients']}", f"{stc['discovery_subset_80']['NP']['patients']} / {stc['discovery_subset_80']['P']['patients']}"]]
for nm, k, pub in (("Mean age at diagnosis ± SD", "age_at_diagnosis", "59.7 ± 10 / 62.4 ± 9.7"),):
    rows.append([nm, pub] + [f"{ms(stc[c]['NP'][k])} / {ms(stc[c]['P'][k])}" for c in ("demographics_full_all", "discovery_subset_80")])
rows.append(["BE segment length cm ± SD (not recorded)", "4.7 ± 2.6 (3) / 4.6 ± 2.4 (12)"] + [f"{ms(stc[c]['NP']['be_length_maximal_cm'])} ({stc[c]['NP']['be_length_not_recorded']}) / {ms(stc[c]['P']['be_length_maximal_cm'])} ({stc[c]['P']['be_length_not_recorded']})" for c in ("demographics_full_all", "discovery_subset_80")])
rows.append(["Female : male", "11:32 / 8:37"] + [f"{stc[c]['NP']['female']}:{stc[c]['NP']['male']} / {stc[c]['P']['female']}:{stc[c]['P']['male']}" for c in ("demographics_full_all", "discovery_subset_80")])
rows.append(["Smoking yes : no (not recorded)", "16:6 (21) / 19:5 (21)"] + [f"{stc[c]['NP']['smoking_Y']}:{stc[c]['NP']['smoking_N']} ({stc[c]['NP']['smoking_not_recorded']}) / {stc[c]['P']['smoking_Y']}:{stc[c]['P']['smoking_N']} ({stc[c]['P']['smoking_not_recorded']})" for c in ("demographics_full_all", "discovery_subset_80")])
rows.append(["Follow-up years, range (mean ± SD)", "3–13 (6.7 ± 3.2) / 1–15 (4.6 ± 3.7)"] + [f"{stc[c]['NP']['followup_range'][0]}–{stc[c]['NP']['followup_range'][1]} ({ms(stc[c]['NP']['followup_years'])}) / {stc[c]['P']['followup_range'][0]}–{stc[c]['P']['followup_range'][1]} ({ms(stc[c]['P']['followup_years'])})" for c in ("demographics_full_all", "discovery_subset_80")])
L += ["**Supplementary Table 1 against our data** (NP / P; our values from `Demographics_full.csv`, `Maximal` as BE segment length, `Total Followup (years)` as follow-up; `d2_st_compare.json`):", ""]
L += table(["Row", "Supplementary Table 1 (published)", "Demographics_full.csv, all rows (P/NP column)", "Discovery subset, 80 (sheet Status)"], rows)
v = stc["validation_sheet_patients_sqlite"]
L += [f"Supplementary Table 2 (validation, 58 NP / 18 P): age at diagnosis 67.1 ± 13 / 62.8 ± 9.7, F:M 14:42 / 4:14, BE length 6.3 ± 3.1 / 5.4 ± 2.9, smoking 14:16 (27) / 11:4 (3). The release's 268-sheet patients with validation-sheet Status, from `BE_Progression_Project.db`: {v['NP']['patients']} NP / {v['P']['patients']} P; age {ms(v['NP']['age_at_diagnosis'])} / {ms(v['P']['age_at_diagnosis'])}; F:M {v['NP']['female']}:{v['NP']['male']} / {v['P']['female']}:{v['P']['male']}; BE length {ms(v['NP']['be_length_maximal_cm'])} / {ms(v['P']['be_length_maximal_cm'])}; smoking (former or current) : never (not recorded) {v['NP']['smoking_yes_former_or_current']}:{v['NP']['smoking_no_never']} ({v['NP']['smoking_not_recorded']}) / {v['P']['smoking_yes_former_or_current']}:{v['P']['smoking_no_never']} ({v['P']['smoking_not_recorded']}).", "",
      "**Result.** Our 43 discovery non-progressors reproduce Supplementary Table 1's non-progressor column exactly, and all 45 progressors in `Demographics_full.csv` reproduce its progressor column exactly; our discovery subset holds 37 of those 45 (the 8 without a UNI2 slide are missing), so its progressor column differs. The 18 validation progressors reproduce Supplementary Table 2 exactly; our validation-sheet non-progressors are 63 against the published 58. Follow-up does not reproduce: `Total Followup (years)` is longer than the published follow-up (NP 8.2 vs 6.7 years), so the paper used another follow-up definition (the sheet also has 'Length of Followup with Sequencing', not compared).",
      "**Method.** `dm_namesearch.py` (search), `dm_supp.py` (appendix tables parsed from the docx XML; Source Data sheet headers), `dm_st1.py` (summaries). **Sources.** As named; `d2_name_search.json`, `d2_supp.json`, `d2_st_compare.json`.",
      "**Caveats.** Supplementary Table 1 reports 'BE segment length' without defining it; Prague M (`Maximal`) reproduces it exactly, so it is taken as M.", ""]
# ---------- D3
L += ["### D3. Database-filled demographics", "", "**Question.** What can the database add, for the discovery subset (80), the release (150) and ACE-B (117)? **Status.** DONE, with NOT AVAILABLE cells. **Pre-specification.** Above (D3).", "",
      f"**Linkage.** Discovery subset: {d3['discovery_linkage']['with_pid']}/80 with a database participant_id, {d3['discovery_linkage']['in_sqlite']}/80 in `BE_Progression_Project.db`. Release: {d3['release_linkage']['with_pid']}/150 and {d3['release_linkage']['in_sqlite']}/150. ACE-B: PatientID → participant_id through `{d3['aceb_linkage']['mapping_file'].split('/')[-1]}` (study_number and participant-id columns only): " + ", ".join(f"{k} {v}" for k, v in d3["aceb_linkage"]["pid_status"].items()) + " of 117.", ""]
V = [("Age at first sample, sheet DOB (years)", "age_first_sample_sheet", "num", "`Demographics_full.csv` Date of birth; first-sample date"), ("Age at first sample, database DOB", "age_first_sample_db", "num", "`initial_history.dob` (ACE-B: participant table)"),
     ("Age at BE diagnosis, sheet", "age_dx_sheet", "num", "`Demographics_full.csv` Age at diagnosis"), ("Age at BE diagnosis, BE progression DB", "age_dx_sqlite", "num", "`BE_Progression_Project.db` Patient.AgeAtDiagnosis"), ("Age at BE diagnosis, database", "age_dx_db", "num", "`initial_history.datediagnosed` − `dob`"),
     ("Sex, sheet", "sex_sheet", "cat", "`Demographics_full.csv` Sex"), ("Sex, BE progression DB", "sex_sqlite", "cat", "Patient.Gender"), ("Sex, participant table (ACE-B)", "sex_participant_table", "cat", "`aceb_sample_counts_per_patient` gender"),
     ("Prague C, sheet (cm)", "prague_c_sheet", "num", "`Demographics_full.csv` Circumference"), ("Prague C, BE progression DB", "prague_c_sqlite", "num", "Patient.Circumference"), ("Prague C, database closest endoscopy", "prague_c_db", "num", "`endoscopy.barretts_circumference`"), ("  gap to first sample (days)", "prague_c_gap", "num", "`endoscopy.endoscopydate`"), ("Prague C, database baseline", "prague_c_ih", "num", "`initial_history.praguec`"),
     ("Prague M, sheet (cm)", "prague_m_sheet", "num", "`Demographics_full.csv` Maximal"), ("Prague M, BE progression DB", "prague_m_sqlite", "num", "Patient.Maximal"), ("Prague M, database closest endoscopy", "prague_m_db", "num", "`endoscopy.barretts_maximum`"), ("  gap to first sample (days)", "prague_m_gap", "num", "`endoscopy.endoscopydate`"), ("Prague M, database baseline", "prague_m_ih", "num", "`initial_history.praguem`"),
     ("Smoking, sheet", "smoking_sheet", "cat", "`Demographics_full.csv` Smoking Status"), ("Smoking, BE progression DB", "smoking_sqlite", "cat", "Patient.SmokingStatus"), ("Smoking, database code (NOT RESOLVED)", "smoking_db_code", "cat", "`initial_history.smoking`"), ("Pack-years, database", "packyears_db", "cat", "`initial_history.packyears`"),
     ("BMI, database (10–80 only)", "bmi_db_num", "num", "`initial_history.bmi`"), ("BMI, BE progression DB", "bmi_sqlite", "num", "Patient.Weight / Height²"), ("Hiatal hernia, database closest endoscopy", "hiatal_hernia_db", "cat", "`endoscopy.hiatusherniapresent`"), ("  gap (days)", "hiatal_hernia_gap", "num", "`endoscopy.endoscopydate`"),
     ("PPI, database code (no codebook)", "ppi_db_code", "cat", "`initial_history.ppi`"), ("Family history of BE, database", "fam_be_db", "cat", "`initial_history.fambarretts`"), ("Family history of OAC, database", "fam_oac_db", "cat", "`initial_history.famoescancer`")]
cov = d3["coverage"]; rows = []
for nm, k, t, src in V:
    cells = []
    for coh, labs in (("discovery", ("all", "P", "NP")), ("release", ("all", "P", "NP")), ("aceb", ("all",))):
        for lab in labs:
            o = cov[coh][lab]; N = o["N"]; x = o.get(k); cells.append((num if t == "num" else cat)(x, N))
    rows.append([nm] + cells + [src])
L += table(["Variable", "Discovery all", "Discovery P", "Discovery NP", "Release all", "Release P", "Release NP", "ACE-B", "Source"], rows)
L += [f"Alcohol (`initial_history.alcoholcurrent`, free text, not categorised) recorded for {cov['discovery']['all']['alcohol_db_recorded']}/80 discovery, {cov['release']['all']['alcohol_db_recorded']}/150 release and {cov['aceb']['all']['alcohol_db_recorded']}/117 ACE-B patients. Ethnicity: NOT AVAILABLE (only the OCCAMS lookup `occams_ethnic_category`, no Barrett's participant link). Sex in the Barrett's database export: NOT AVAILABLE (" + d3["sex_in_db_tables"] + ").", "",
      f"Database Prague values at the closest endoscopy are more than 365 days from the first sample for {cov['discovery']['all']['prague_c_db_gap_gt_365']}/{cov['discovery']['all']['prague_c_db']['n']} discovery and {cov['release']['all']['prague_c_db_gap_gt_365']}/{cov['release']['all']['prague_c_db']['n']} release patients (all flagged). Database BMI values outside 10–80 (0 or negative): {cov['discovery']['all']['bmi_db_implausible']} discovery, {cov['release']['all']['bmi_db_implausible']} release, {cov['aceb']['all']['bmi_db_implausible']} ACE-B. Database age at first sample below 18 years (implausible date of birth): {ag['discovery']['age_first_sample_db_below_18']} discovery, {ag['release']['age_first_sample_db_below_18']} release.", "",
      "**Agreement between sources** (patients with both):", ""]
rows = []
for coh in ("discovery", "release"):
    a = ag[coh]; rows += [[coh, "sex, sheet vs BE progression DB", f"{a['sex']['agree']}/{a['sex']['both']}"], [coh, "age at diagnosis, sheet vs BE progression DB (±0.5 y)", f"{a['age_dx']['agree_within_0.5y']}/{a['age_dx']['both']}"],
                          [coh, "Prague C / M, sheet vs BE progression DB", f"{a['prague_c']['agree']}/{a['prague_c']['both']} / {a['prague_m']['agree']}/{a['prague_m']['both']}"], [coh, "smoking, sheet Y/N vs DB never ↔ N, former/current ↔ Y", f"{a['smoking']['agree_Y_eq_former_or_current']}/{a['smoking']['both']}"],
                          [coh, "age at diagnosis, database vs sheet: within 1 y (median |Δ|)", f"{a['age_dx_db_minus_age_dx_sheet']['within_1y']}/{a['age_dx_db_minus_age_dx_sheet']['both']} ({a['age_dx_db_minus_age_dx_sheet']['median_abs_years']} y)"],
                          [coh, "age at first sample, database vs sheet DOB: within 1 y (median |Δ|)", f"{a['age_first_sample_db_minus_age_first_sample_sheet']['within_1y']}/{a['age_first_sample_db_minus_age_first_sample_sheet']['both']} ({a['age_first_sample_db_minus_age_first_sample_sheet']['median_abs_years']} y)"],
                          [coh, "patients with sex / smoking only in the BE progression DB", f"{a['sqlite_only_patients_sex']} / {a['sqlite_only_patients_smoking']}"]]
L += table(["Cohort", "Comparison", "Agree / both"], rows)
mr = d3["missing_representation_initial_history_rows_of_cohort_patients"]
L += ["**How missing values are represented** (`initial_history` records of the cohorts' participants; `endoscopy` all rows; `BE_Progression_Project.db` Patient):", ""]
L += table(["Table.column", "NaN/None object", "''", "'None'", "0", "Rows"], [[f"initial_history.{k}", v["NaN_or_None_object"], v["empty_string"], v["string_None"], v["zero"], v["n"]] for k, v in mr.items()] +
           [[f"endoscopy.{k}", v["NaN_or_None_object"], v["empty_string"], v["string_None"], v["zero"], v["n"]] for k, v in d3["missing_representation_endoscopy"].items()] +
           [[f"Patient.{k}", v["NaN_or_None_object"], v["empty_string"], v["string_None"], v["zero"], v["n"]] for k, v in d3["missing_representation_sqlite_patient"].items()])
L += ["**Method.** `dm_analyse.py` PART=d3 and `dm_agree.py`. A participant's `initial_history` value is used only when all its records agree; otherwise it is counted as a conflict and left missing. No imputation.",
      "**Sources.** As in the table; `d3.json`, `d3_agree.json`.",
      "**Caveats.** (1) The database endoscopy records start years after the discovery samples (closest gap median about 12 years), so their Prague values describe a later Barrett's segment, not the one at sampling. (2) Every linked patient's closest endoscopy has `hiatusherniapresent` = 1, against 5,581 '1' and 4,362 '0' in the whole table; this may be a form default, as with the zeros in `initial_history`. (3) `BE_Progression_Project.db` reproduces the sheet exactly where both exist and extends it to the validation-sheet patients; it is a project database, not the Barrett's clinical database. (4) ACE-B: age at first sample and endoscopy-dated variables need biopsy dates, which were not read.", ""]
# ---------- D4
dg = {"all": dd["all"]["baseline_grade"], "P": dd["P"]["baseline_grade"], "NP": dd["NP"]["baseline_grade"]}
rows = []
T1 = [("Age at first sample (years)", "age_first_sample_sheet", "num", "sheet"), ("Age at BE diagnosis (years)", "age_dx_sheet", "num", "sheet"), ("Age at BE diagnosis (years)", "age_dx_db", "num", "database"),
      ("Sex", "sex_sheet", "cat", "sheet"), ("Sex", "sex_participant_table", "cat", "database (participant table)"), ("Prague C (cm)", "prague_c_sheet", "num", "sheet"), ("Prague C (cm), baseline", "prague_c_ih", "num", "database"),
      ("Prague M (cm)", "prague_m_sheet", "num", "sheet"), ("Prague M (cm), baseline", "prague_m_ih", "num", "database"), ("Smoking", "smoking_sheet", "cat", "sheet"), ("Smoking", "smoking_sqlite", "cat", "BE progression DB"),
      ("Smoking code (not resolved)", "smoking_db_code", "cat", "database"), ("BMI (10–80)", "bmi_db_num", "num", "database"), ("BMI", "bmi_sqlite", "num", "BE progression DB"), ("Hiatal hernia (closest endoscopy, all > 1 y away)", "hiatal_hernia_db", "cat", "database"),
      ("PPI code (no codebook)", "ppi_db_code", "cat", "database")]
for nm, k, t, src in T1:
    cells = [(num if t == "num" else cat)(cov["discovery"][lab].get(k), cov["discovery"][lab]["N"]) for lab in ("all", "P", "NP")] + [(num if t == "num" else cat)(cov["aceb"]["all"].get(k), 117)]
    rows.append([nm, src] + cells)
rows.append(["Baseline grade (first set C sample)", "sheet (`docs/dataset_description.md` item 4)"] + [", ".join(f"{k} {v}" for k, v in dg[l].items()) + f" ({sum(dg[l].values())}/{cov['discovery'][l]['N']})" for l in ("all", "P", "NP")] + ["not read (pathology)"])
rows.append(["Ethnicity, family history", "—", "NOT AVAILABLE", "NOT AVAILABLE", "NOT AVAILABLE", "NOT AVAILABLE"])
L += ["### D4. Updated Table 1", "", "Discovery subset by label (37 P, 43 NP) and ACE-B (117, no labels). Median [IQR] (n/N) for numbers; counts (n/N) for categories. Source: sheet = `Demographics_full.csv`; BE progression DB = `BE_Progression_Project.db` (identical to the sheet where both exist); database = Barrett's DB export or its participant-table scrape.", ""]
L += table(["Variable", "Source", "Discovery all (80)", "Discovery P (37)", "Discovery NP (43)", "ACE-B (117)"], rows)
L += ["### Discrepancies found", "",
      "- The pre-specified default-value test for code 0 is degenerate: the lowest tercile of record completeness is the 3,024 all-'None' records, where smoking is null rather than 0.",
      "- `BE_Progression_Project.db` sits in the ACE-B metadata folder but holds the SWG / Killcoyne progression project (165 patients); it is read here for SWG patients only, demographic columns only.",
      "- Database dates of birth disagree with the sheet for a few patients (age at first sample below 18 in 2 discovery patients).",
      "- `packyears` holds a year ('2003') for one patient.", "",
      "### Not done", "",
      "- The Supplementary Information PDF (`MOESM1`) and Reporting Summary (`MOESM2`) are not on the cluster and were not downloaded; the PMC appendix carries the same supplementary tables.",
      "- The Barrett's database REST API (`api.barrettsdatabase.org.uk`, used by `scripts/export_barretts_db.py`) was not queried for a schema or field definitions; the export code holds none.",
      "- Any mapping of the smoking codes (NOT RESOLVED by the rule) and of the PPI codes (no codebook).",
      "- ACE-B age at first sample, dated Prague and hiatal hernia (biopsy dates not read).", "",
      "**Interpretation.** The database cannot decode smoking or add dated Prague values for these cohorts; the project database fills sex, age at diagnosis, Prague and smoking for the validation-sheet patients, and ACE-B gains sex for 52 of 117 patients.", ""]
open(DOC, "w").write("\n".join(L) + "\n"); print("rendered", len(L))
