"""Render Results of docs/paper_horizon_q2_all_horizons.md from results/paper_final/horizon_q2_all/q2_all.json. Usage: python hq_render.py RESULTS_COMMIT"""
import json, sys
RC = sys.argv[1]; DOC = "docs/paper_horizon_q2_all_horizons.md"; d = json.load(open("results/paper_final/horizon_q2_all/q2_all.json")); H = d["horizons"]
def table(h, rows): return ["| " + " | ".join(h) + " |", "|" + "|".join("---" for _ in h) + "|"] + ["| " + " | ".join(map(str, r)) + " |" for r in rows] + [""]
ms = lambda o: f"{o['mean']:.1f} (SD {o['sd']:.1f})"
cap = lambda t: H[t]["captured_cases_CNVneg_bestpos"]; both = lambda t: H[t]["cases_both_pos"]; clr = lambda t: H[t]["cleared_controls_CNVpos_bestneg"]
L = open(DOC).read().split("\n## Results")[0].rstrip().split("\n")
ok = all(all(v for v in H[t]["check_vs_q2json"].values()) for t in H)
L += ["", "## Results", "", f"Pre-specification commit e645dcf; results commit {RC}. Script `scripts/paper_plan/hq_all.py` (Slurm, prefix hq), `scripts/paper_plan/hq_render.py`. Aggregates `results/paper_final/horizon_q2_all/q2_all.json`. Source rows: the Q2 per-sample list from `ha_q2.py` (afa0278), cluster-only; patient lists for this document: `feasibility/paper_plan/killcoyne_mm/horizon_answers/q2_all_horizons_patients.csv` (cluster only).", "",
      "### Status", ""] + table(["Item", "Status"], [["Breakdown at 1, 3 and 5 years", "DONE"], ["Counts equal `q2.json` (afa0278)", "yes, every horizon" if ok else "NO, see JSON"], ["Published probability: MOESM4 vs `set_C.csv` k_prob", f"identical (max |difference| {d['prob_match_moesm4_vs_kprob_max_abs_diff']})"], ["Was 3 years a pre-specified primary horizon?", "No (details below)"]])
rows = []
for t in ("1", "3", "5"):
    rows.append([f"{t} year{'s' if t != '1' else ''}", f"{cap(t)['samples']} / {cap(t)['patients']}", f"{clr(t)['samples']} / {clr(t)['patients']}", ms(cap(t)["cx_raw_pkg"]), ms(both(t)["cx_raw_pkg"]), ms(cap(t)["tissue_tiles"]), ms(both(t)["tissue_tiles"]),
                 f"{cap(t)['pub_prob_le_0.3']} / {cap(t)['samples']}", f"{both(t)['pub_prob_le_0.3']} / {both(t)['samples']}", f"{both(t)['samples']} / {both(t)['patients']}"])
L += ["### Late fusion vs CNV (their matrix), all pre-event samples", "", "Newly caught = cases negative under L-CNV and positive under L-LATE; newly cleared = controls positive under L-CNV and negative under L-LATE. Samples / patients. Means of raw cx (package block) and tissue tiles; published Pr ≤ 0.3 = Killcoyne's published probability (MOESM4).", ""]
L += table(["Horizon", "Cases newly caught", "Controls newly cleared", "cx, newly caught", "cx, caught by both", "Tiles, newly caught", "Tiles, caught by both", "Newly caught with published Pr ≤ 0.3", "Caught by both with Pr ≤ 0.3", "Cases caught by both"], rows)
L += ["### Answer", "",
      f"At every horizon late fusion clears more control samples than it newly catches case samples: {cap('1')['samples']} caught vs {clr('1')['samples']} cleared at 1 year, {cap('3')['samples']} vs {clr('3')['samples']} at 3 years and {cap('5')['samples']} vs {clr('5')['samples']} at 5 years. "
      f"The newly caught cases are mostly ones Killcoyne's published model scored low risk at 3 and 5 years ({cap('3')['pub_prob_le_0.3']}/{cap('3')['samples']} and {cap('5')['pub_prob_le_0.3']}/{cap('5')['samples']} with Pr ≤ 0.3) and have lower CNV complexity than cases both models catch (mean cx {cap('3')['cx_raw_pkg']['mean']:.1f} vs {both('3')['cx_raw_pkg']['mean']:.1f}, {cap('5')['cx_raw_pkg']['mean']:.1f} vs {both('5')['cx_raw_pkg']['mean']:.1f}); "
      f"at 1 year the 6 newly caught samples (3 patients) do not follow that pattern (cx {cap('1')['cx_raw_pkg']['mean']:.1f} vs {both('1')['cx_raw_pkg']['mean']:.1f}; {cap('1')['pub_prob_le_0.3']}/6 low risk). Newly caught cases have fewer tissue tiles on average at every horizon, with wide spread. One line: the 3-year pattern holds at 5 years but rests on 3 patients at 1 year.", "",
      "### Was 3 years a pre-specified primary horizon?", "",
      "No. No pre-specification commit designates a primary horizon for the AUROCs or for Q2:",
      "- `81473df` (2026-10-05, pre-specification of `docs/paper_horizon_answers.md`, whose Q2 produced these numbers): horizons 1, 3 and 5 years are treated alike; Q2 asks for every comparison \"at each horizon\" and for the newly captured / cleared groups without naming a horizon. The 3-year emphasis in that document's Q2 answer was a reporting choice made after the results, not pre-specified.",
      "- `ee51db8` (2026-10-01, pre-specification of `docs/paper_survival_horizons.md`) is the only commit that names 3 years, and only for the descriptive breakdown of H2, which used a different operating point (80% sensitivity for the ever-progression label): \"Operating point (a), 3-year horizon, their matrix, best model and L-LATE; the other cells' counts reported.\"",
      "- `2d0014f` (fold-stratified AUROC) and `487b2a7` (grade row) do not designate a primary horizon.", "",
      "**Method.** No new predictions or thresholds: the groups are those of `ha_q2.py` (afa0278) at each horizon; this script only adds means, SDs and the published-probability count. **Sources.** `q2_patient_list.csv` (cluster), `killcoyne_data_from_paper/41591_2020_1033_MOESM4_ESM.xlsx` ('Supporting data for Figure 2a' `Probability`), `models/killcoyne_frozen_pkg_v1/cnv_scaling_setC.csv` (raw cx), `horizons/slide_desc.csv` (tiles).",
      "**Caveats.** (1) The operating point is fitted for each horizon's cases, so the three horizons use different thresholds; the groups are not nested. (2) Samples, not patients, are the unit of the means; several samples come from the same patient. (3) Tile counts are highly skewed (SDs exceed the means), so the mean difference in tiles is not robust to a few large slides; the medians were reported in `docs/paper_horizon_answers.md`. (4) Design caveat: matched case–control cohort; no absolute risks or PPVs.", ""]
open(DOC, "w").write("\n".join(L) + "\n"); print("rendered", len(L))
